##########################################
## Foto OBRIR porta garatge
##
- alias: 'empieza lluvia'
  trigger:   
    - platform: template
      value_template: "{% if states.sensor.meteocarlet_rain_rate.state | float > 0.01 %} true {% endif %}"      
  action:
    service: notify.AireCarlet
    data_template:
      title: "Empieza la lluvia"
      message: "({{ states.sensor.meteocarlet_rain_rate.state }} mm)"

- alias: 'termina lluvia'
  trigger:   
      entity_id: sensor.meteocarlet_forecast
      platform: state
      from: rain
  action:
    service: notify.AireCarlet
    data_template:
      title: "Termina la lluvia"
      message: "({{ states.sensor.meteocarlet_rain_rate.state }} mm)"              
