##########################################
## Sonoff basic http://192.168.3.77/
## NEUTRO
#- platform: mqtt
#  name: "sonoffbasic"
#  state_topic: "stat/sonoffbasic/POWER"
#  command_topic: "cmnd/sonoffbasic/POWER"
#  qos: 1
#  payload_on: "ON"
#  payload_off: "OFF"
#  optimistic: false
#  retain: true
#  icon: mdi:car

##########################################
## Sonoff basic http://192.168.3.85/
## VENTILADOR
#- platform: mqtt
#  name: "sonoffbasic2"
#  state_topic: "stat/sonoffbasic2/POWER"
#  command_topic: "cmnd/sonoffbasic2/POWER"
#  qos: 1
#  payload_on: "ON"
#  payload_off: "OFF"
#  optimistic: false
#  retain: true
#  icon: mdi:fan
