##########################################
## BlitzWolf SHP2 http://192.168.3.88
## medidorconsumo 
##
- platform: mqtt
  name: bw1_total
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total }}"
  unit_of_measurement: "kW/h"

- platform: mqtt
  name: bw1_total_euro
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total | multiply(0.145) | round(2) }}"
  unit_of_measurement: "€"
    
- platform: mqtt
  name: bw1_yesterday
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday }}"
  unit_of_measurement: "kW/h"  
  
- platform: mqtt
  name: bw1_yesterday_euro
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday | multiply(0.145) | round(2) }}"
  unit_of_measurement: "€"  
  
- platform: mqtt
  name: bw1_today
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Today }}"
  unit_of_measurement: "kW/h"  
  
- platform: mqtt
  name: bw1_power
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Power }}"
  unit_of_measurement: "W"

- platform: mqtt
  name: bw1_factor
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Factor }}"

- platform: mqtt
  name: bw1_voltage
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Voltage }}"
  unit_of_measurement: "V"

- platform: mqtt
  name: bw1_current
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Current }}"
  unit_of_measurement: "A" 
  
#- platform: mqtt
#  name: "Enchufe W"
#  state_topic: "tele/medidorconsumo/SENSOR"
#  value_template: "{{ value_json['ENERGY'].Power }}"
#  unit_of_measurement: "W"
#
#- platform: mqtt
#  name: "Enchufe Voltaje"
#  state_topic: "tele/medidorconsumo/SENSOR"
#  value_template: "{{ value_json['ENERGY'].Voltage }}"
#  unit_of_measurement: "V"

