log_all:
  name: Log All
  #initial: off
  icon: mdi:record-rec

confirmacion_alarma:
  name: ConfirmacionAlarma
  initial: off
  icon: mdi:alarm-light
  
confirmacion_puerta:
  name: ConfirmacionPuerta
  initial: off
  icon: mdi:lock-open

confirmacion_puerta_garaje:
  name: ConfirmacionPuertaGaraje
  initial: off
  icon: mdi:lock-open
  
en_vacaciones:
  name: En Vacaciones
  icon: mdi:weather-sunny
  
#dash_button_1:
#  initial: off

####################
##### Programador    
programweekday1:
    name: Weekdays Only
    icon: mdi:calendar
programonlyonce1:
    name: Only once time
    icon: mdi:calendar