gateway_sound:
  name: Ringtone
  icon: mdi:music-note
  options: 
      - "0 - Police car 1"
      - "1 - Police car 2"
      - "2 - Accident"
      - "3 - Countdown"
      - "4 - Ghost"
      - "5 - Sniper rifle"
      - "6 - Battle"
      - "7 - Air raid"
      - "8 - Bark"
      - "10 - Doorbell"
      - "11 - Knock at a door"
      - "12 - Amuse"
      - "13 - Alarm clock"
      - "20 - MiMix"
      - "21 - Enthusiastic"
      - "22 - GuitarClassic"
      - "23 - IceWorldPiano"
      - "24 - LeisureTime"
      - "25 - ChildHood"
      - "26 - MorningStreamLiet"
      - "27 - MusicBox"
      - "28 - Orange"
      - "29 - Thinker"
      - "10001 - res"
      - "10002 - Timbre"
      - "10003 - Cancion"
      - "10004 - Alarm Sound 1"
      - "10005 - Silvido (alarma)"
      - "10006 - Puerta garaje más 10 min"
      - "10007 - xx"
      - "10008 - xx"
      - "10009 - xx"
      - "10010 - xx"
      - "10011 - xx"
      - "10012 - xx"
      - "10013 - xx"
      - "10014 - xx"
      - "10015 - xx"
      - "10016 - xx"
      - "10017 - xx"
      - "10018 - xx"