##########################################
## BlitzWolf SHP2 http://192.168.3.88
## medidorconsumo 
##
- platform: mqtt
  name: bw1_total
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total }}"
  unit_of_measurement: "kW/h"

- platform: mqtt
  name: bw1_total_euro
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Total | multiply(0.145) | round(2) }}"
  unit_of_measurement: "€"
    
- platform: mqtt
  name: bw1_yesterday
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday }}"
  unit_of_measurement: "kW/h"  
  
- platform: mqtt
  name: bw1_yesterday_euro
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Yesterday | multiply(0.145) | round(2) }}"
  unit_of_measurement: "€"  
  
- platform: mqtt
  name: bw1_today
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Today }}"
  unit_of_measurement: "kW/h"  
  
- platform: mqtt
  name: bw1_power
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Power }}"
  unit_of_measurement: "W"

- platform: mqtt
  name: bw1_factor
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Factor }}"

- platform: mqtt
  name: bw1_voltage
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Voltage }}"
  unit_of_measurement: "V"

- platform: mqtt
  name: bw1_current
  state_topic: "tele/medidorconsumo/SENSOR"
  value_template: "{{ value_json['ENERGY'].Current }}"
  unit_of_measurement: "A" 
  
#- platform: mqtt
#  name: "Enchufe W"
#  state_topic: "tele/medidorconsumo/SENSOR"
#  value_template: "{{ value_json['ENERGY'].Power }}"
#  unit_of_measurement: "W"
#
#- platform: mqtt
#  name: "Enchufe Voltaje"
#  state_topic: "tele/medidorconsumo/SENSOR"
#  value_template: "{{ value_json['ENERGY'].Voltage }}"
#  unit_of_measurement: "V"
  
## 
## FIN medidorconsumo 
############################################   
- platform: systemmonitor 
  name: Domopi
  # en segundos (1 hora)
  scan_interval: 3600
  resources: 
      - type: disk_use_percent 
        arg: /home 
      - type: memory_free 
      - type: processor_use 
      - type: last_boot 
      - type: since_last_boot
#      - type: disk_free 
#        arg: /

- platform: systemmonitor
  resources:
    - type: process
      arg: mosquitto

- platform: pi_hole

#sensor clientraw
#reads info from clientraw.txt from meteo stations on Internet from URL.
#needs .homeassistant/custom_components/sensor/clientraw.py
#from: https://github.com/pilotak/HomeAssistant-MyConfig/tree/master/custom_components/sensor
- platform: clientraw
  interval: 15
  name: meteocarlet
  url: !secret clientrawURL
  monitored_conditions:
    - temp
    - wind_dir
    - wind_gust_kph
    - wind_kph
    - symbol
    - forecast
    - rain_rate
    - pressure
    - humidity
      
- platform: clientraw
  interval: 5
  name: meteolalcudia
  url: !secret clientrawURL2
  monitored_conditions:
    - temp
    - wind_dir
    - wind_gust_kph
    - wind_kph
    - symbol
    - forecast
    - rain_rate
    - pressure
    - humidity

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'time_date'
    - 'time_utc'

- platform: template
  sensors:
    timer1_time:
      friendly_name: 'start time'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.timer1_hour") | int, states("input_number.timer1_minutes") | int) }}'
    timer1_duration:
      friendly_name: 'duration'  
      value_template: '{{ "%0.02d:%0.02d" | format(0 | int, states("input_number.timer1_duration") | int) }}'  

- platform: template
  sensors:
    bateria_porta_garatge:
      friendly_name: 'Porta garatge'
      value_template: >
        {%- if states.binary_sensor.door_window_sensor_158d0001a7eafb.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d0001a7eafb.attributes.battery_level|round }}
        {% else %}
          {{ states.binary_sensor.door_window_sensor_158d0001a7eafb.state }}
        {%- endif %}
      icon_template: '{%- if  states.binary_sensor.door_window_sensor_158d0001a7eafb.attributes.battery_level <= 5 %}mdi:battery-outline{%- elif states.binary_sensor.door_window_sensor_158d0001a7eafb.attributes.battery_level >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.binary_sensor.door_window_sensor_158d0001a7eafb.attributes.battery_level|float / 10)|round*10}}{%- endif %}'
      unit_of_measurement: "%"
    bateria_porta_entrada:
      friendly_name: 'Porta entrada'
      value_template: >
        {%- if states.binary_sensor.door_window_sensor_158d0001b7bd84.attributes.battery_level %}
            {{ states.binary_sensor.door_window_sensor_158d0001b7bd84.attributes.battery_level|round }}
        {% else %}
          {{ states.binary_sensor.door_window_sensor_158d0001b7bd84.state }}
        {%- endif %}
      icon_template: '{%- if  states.binary_sensor.door_window_sensor_158d0001b7bd84.attributes.battery_level <= 5 %}mdi:battery-outline{%- elif states.binary_sensor.door_window_sensor_158d0001b7bd84.attributes.battery_level >= 95 %}mdi:battery{% else %}mdi:battery-{{(states.binary_sensor.door_window_sensor_158d0001b7bd84.attributes.battery_level|float / 10)|round*10}}{%- endif %}'
      unit_of_measurement: "%"  
    bateria_presencia1:
      friendly_name: 'Presencia 1'
      value_template: >
        {%- if states.binary_sensor.motion_sensor_158d000222e398.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d000222e398.attributes.battery_level|round }}
        {% else %}
          {{ states.binary_sensor.motion_sensor_158d000222e398.state }}
        {%- endif %}
      icon_template: '{%- if  states.binary_sensor.motion_sensor_158d000222e398.attributes.battery_level <= 5 %}
                        mdi:battery-outline
                      {%- elif states.binary_sensor.motion_sensor_158d000222e398.attributes.battery_level >= 95 %}
                        mdi:battery
                      {% else %}
                        mdi:battery-{{(states.binary_sensor.motion_sensor_158d000222e398.attributes.battery_level|float / 10)|round*10}}
                      {%- endif %}'
      unit_of_measurement: "%" 
    bateria_presencia2:
      friendly_name: 'Presencia 2'
      value_template: >
        {%- if states.binary_sensor.motion_sensor_158d0001f9d516.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d0001f9d516.attributes.battery_level|round }}
        {% else %}
          {{ states.binary_sensor.motion_sensor_158d0001f9d516.state }}
        {%- endif %}
      icon_template: '{%- if  states.binary_sensor.motion_sensor_158d0001f9d516.attributes.battery_level <= 5 %}
                        mdi:battery-outline
                      {%- elif states.binary_sensor.motion_sensor_158d0001f9d516.attributes.battery_level >= 95 %}
                        mdi:battery
                      {% else %}
                        mdi:battery-{{(states.binary_sensor.motion_sensor_158d0001f9d516.attributes.battery_level|float / 10)|round*10}}
                      {%- endif %}'
      unit_of_measurement: "%"  
    bateria_presencia3:
      friendly_name: 'Presencia 3'
      value_template: >
        {%- if states.binary_sensor.motion_sensor_158d000236b6a6.attributes.battery_level %}
            {{ states.binary_sensor.motion_sensor_158d000236b6a6.attributes.battery_level|round }}
        {% else %}
          {{ states.binary_sensor.motion_sensor_158d000236b6a6.state }}
        {%- endif %}
      icon_template: '{%- if  states.binary_sensor.motion_sensor_158d000236b6a6.attributes.battery_level <= 5 %}
                        mdi:battery-outline
                      {%- elif states.binary_sensor.motion_sensor_158d000236b6a6.attributes.battery_level >= 95 %}
                        mdi:battery
                      {% else %}
                        mdi:battery-{{(states.binary_sensor.motion_sensor_158d000236b6a6.attributes.battery_level|float / 10)|round*10}}
                      {%- endif %}'
      unit_of_measurement: "%"  