
rebootpi: 'sudo reboot'

take_snapshot: 'rm /home/homeassistant/capturas/captura1.jpg; ffmpeg -rtsp_transport -udp_multicast -i rtsp://192.168.3.70:554/ch0_0.h264 -f image2 -vframes 1 -pix_fmt yuvj420p /home/homeassistant/capturas/captura1.jpg'

take_video: 'rm /home/homeassistant/capturas/video.avi; ffmpeg -rtsp_transport -udp_multicast -i  rtsp://192.168.3.70:554/ch0_0.h264 -vcodec copy -t 6 -y /home/homeassistant/capturas/video.avi'

cmd_reboot_pi: reboot

# Qué usuario ejecuta HA? para ponerlo en sudoers y que pueda reiniciar
cmd_whoami: whoami > /tmp/whoami.txt

meteo_snapshot: "rm /home/homeassistant/capturas/meteo.png; wget -q -O /home/homeassistant/capturas/meteo.png http://inforatge.com/administrador/mapa-hui.png"
